---
title: "Our Experience Data Analysis"
author: "Anna Li"
date: "10/24/2020"
output: html_document
---

First, just to import all the libraries and data files I'll need.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
setwd("~/Documents/pitt challenge")
getwd()

#import libraries
library(stringr)
library(plyr)
library(dplyr)
library(ggplot2)
library("gridExtra")
library(reshape2)
library("ggsignif")
library(tidyverse)

#import file into 'origfile'
library(readstata13)
origdf <- read.csv(file='data.csv')
```

Next, categorize the birth control methods and pills.
```{r categorizing, include=TRUE}
#1. new column for birth control type
origdf$bctype <- 'na'
origdf$drugv2 <- 'na'
IUDs <- c("Kyleena","Liletta","Mirena","Paraguard","Skyla")
for (row in 1:nrow(origdf)){
    bc <- origdf[row, "drug"]
    bc <- levels(droplevels(bc))
    bc <- substr(bc, 2, nchar(bc))
    origdf[row,"drugv2"] <- bc
    if (bc %in% IUDs){
      origdf[row,"bctype"] <- "IUD"
    }
    else if (bc == "Nexaplon"){
      origdf[row,"bctype"] <- "Nexaplanon (implant)"
    }
    else if (bc == "NuvaRing"){
      origdf[row,"bctype"] <- "NuvaRing"
    }
    else if (bc == "Depo Shot (Depo-Provera)"){
      origdf[row,"bctype"] <- "Depo Shot"
    }
    else{
      origdf[row,"bctype"] <- "Pill"
    }
}

#2. new column for pill type-- fill in if applicable or write na
origdf$pilltype <- 'na' #create the new column

#create groups that we're going to filter by
desogestrel <- c("Apri","Cyclessa","Emoquette","Kariva","Mircette","Reclipsen","Solia")
drospirenone <- c("Loryna","Ocella","Vestura","Yasmin","Yaz")
levonorgestrel <- c("Aviane","Enpresse","Levora","Orsythia","Trivora-28")
norethindrone_acetate <- c("Aranelle","Brevicon","Estrostep Fe","Femcon FE","Generess Fe","Junel 1.5/30","Lo Loestrin Fe","Loestrin 1.5/30","Minastrin 24 Fe","Ovcon 35","Tilia Fe","Tri-Norinyl","Wera","Zenchent Fe")
norgestrel <- c("Cryselle 28","Low-Ogestrel","Ogestrel-28")

#loop through the dataframe to categorize each response
for (row in 1:nrow(origdf)){
  if (origdf[row,"bctype"] == "Pill"){ 
    pill <- origdf[row,"drugv2"]
    if (pill %in% desogestrel){
      origdf[row,"pilltype"] <- "desogestrel"
    }
    else if (pill %in% drospirenone){
      origdf[row,"pilltype"] <- "drospirenone"
    }
    else if (pill %in% levonorgestrel){
      origdf[row,"pilltype"] <- "levonorgestrel"
    }
    else if (pill %in% norethindrone_acetate){
      origdf[row,"pilltype"] <- "norethindrone_acetate"
    }
    else if (pill %in% norgestrel){
      origdf[row,"pilltype"] <- "norgestrel"
    }
    else{
      origdf[row,"pilltype"] <- "other pill"
    }
  }
}
```

Clean up "ages" so each is a decade...
```{r age cleanup, include=T}
for (row in 1:nrow(origdf)){
  age <- origdf[row,"age"]
  check <- age%%10
  if (check != 0){
    if (check > 5){ #round up
      origdf[row,"age"] <- ((age%/%10)+1)*10
    }
    else if (check <= 5){ #round down
      origdf[row,"age"] <- (age%/%10)*10
    }
  }
}
```

Great! Time to start graphing and looking at the data.
To start with, let's see how many responses we have for each category.
```{r response numbers}
count <- function(df, colname){ #df = dataframe
  w <- table(df[,colname])
  t <- as.data.frame(w)
  names(t)[1] = colname
  names(t)[2] = "freq"
  return(t)
}
table <- count(origdf, 'bctype')
ggplot(table, aes(x=bctype, y=freq, fill=bctype)) + geom_bar(stat='identity') + labs(y="Number of Responses", x="Birth Control Type") + ggtitle("Number of Responses by Birth Control Type") + theme_bw() + theme(legend.position = "none")

table1 <- count(origdf,'pilltype')
table1 <- table1[-c(4),] #removes the na row
ggplot(table1, aes(x=pilltype, y=freq, fill=pilltype)) + geom_bar(stat='identity') + labs(y="Number of Responses", x="Pill Type (0.03 mg EE + )") + ggtitle("Number of Responses by Pill Category (for Pills Only)") + theme_bw() + theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust=1))
```

What side effects are the most common?
```{r side effect prevalence, include=T}
#calculate side effect frequencies given a dataframe
#for the overall results:
side_effects <- c("nausea","breasttenderness","acne","weightgain","spotting","amenorrhea","heavyperiod")
sefreq <- function(dataset){
  origdf_sideeffectsonly <- dataset[,side_effects]
  side_effect_freqs <- data.frame(matrix(ncol=2,nrow=length(side_effects)))
  colnames(side_effect_freqs) <- c("Side_Effect","Proportion")
  for (row in 1:nrow(side_effect_freqs)){
    side_effect_freqs[row,"Side_Effect"] <- side_effects[row]
    num_true <- count(dataset,side_effects[row])[2,2]
    total <- sum(count(dataset,side_effects[row])[2])
    prop <- num_true/total
    side_effect_freqs[row,"Proportion"] <- prop
  }
  return (side_effect_freqs)
}

all_ses <- sefreq(origdf)

#graphs
ggplot(all_ses, aes(x=Side_Effect, y=Proportion, fill=Side_Effect)) + geom_bar(stat='identity') + theme_bw() + theme(legend.position='none', axis.text.x= element_text(angle=45, hjust=1)) + ggtitle("All Side Effects Reported")
```

Do the side effects group by type of birth control?
```{r side effects by birth control, include=TRUE} 
#for IUDs #All of these look the same? fix it?
IUDs_only <- origdf[which(origdf$bctype=="IUD"),]
IUD_ses <- sefreq(IUDs_only)
ggplot(IUD_ses, aes(x=Side_Effect, y=Proportion, fill=Side_Effect)) + geom_bar(stat='identity') + theme_bw() + theme(legend.position='none', axis.text.x= element_text(angle=45, hjust=1)) + ggtitle("Side effects reported for IUDs") + ylim(0,1.0)
paste("Number of responses: ",nrow(IUDs_only))

#for pills
Pills_only <- origdf[which(origdf$bctype=="Pill"),]
Pills_ses <- sefreq(Pills_only)
ggplot(Pills_ses, aes(x=Side_Effect, y=Proportion, fill=Side_Effect)) + geom_bar(stat='identity') + theme_bw() + theme(legend.position='none', axis.text.x= element_text(angle=45, hjust=1)) + ggtitle("Side effects reported for Pills") + ylim(0,1.0)
paste("Number of responses: ",nrow(Pills_only))

#for women ≤ 30
under30 <- origdf[which(origdf$age <= 30),]
under30_ses <- sefreq(under30)
ggplot(under30_ses, aes(x=Side_Effect, y=Proportion, fill=Side_Effect)) + geom_bar(stat='identity') + theme_bw() + theme(legend.position='none', axis.text.x= element_text(angle=45, hjust=1)) + ggtitle("Side effects reported for Women Under 30") + ylim(0,1.0)
paste("Number of responses: ",nrow(under30))

#for women > 30
over30 <- origdf[which(origdf$age > 30),]
over30_ses <- sefreq(over30)
ggplot(over30_ses, aes(x=Side_Effect, y=Proportion, fill=Side_Effect)) + geom_bar(stat='identity') + theme_bw() + theme(legend.position='none', axis.text.x= element_text(angle=45, hjust=1)) + ggtitle("Side effects reported for Women Over 30") + ylim(0,1.0)
paste("Number of responses: ",nrow(over30))
```


```{r side effects by demographic, include=TRUE}
#Do the side effects group by type of demographic?
#more machine learning/stats to be done here
```

